# Set user, if any, then global directories for configuration files
# confdirs:
# - "~/.config/nicy"
# - "/usr/local/etc/nicy"
# - "/etc/nicy"

# Set nicy read-only library directory
# libdir: "/usr/lib/nicy"

# Show what command is launched and some more information from systemd-run
# verbose: false

# Use this shell when writing scripts
# shell: "/bin/sh"

# Use this command when root-credentials are required
# sudo: "sudo"

# Use this path to install scripts
# scripts: "~/bin/nicy"
# Superuser
# scripts: "/usr/local/bin/nicy"

# Ignore the commands listed in this file when installing scripts
# ignore: "~/.config/nicy/ignore"

# Symlink the scripts of the corresponding commands listed in this file after installing them
# symlink: "~/.config/nicy/symlink"
